services:
  recommendation-service:
    build: ./backend/recommendation-service
    env_file:
      - ./backend/recommendation-service/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/recommendation-service/app:/app/app
      - ./data:/data
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  tracking-service:
    build: ./backend/tracking-service
    env_file:
      - ./backend/tracking-service/.env
    network_mode: "host"
